import { Link } from 'react-router-dom';
import { ArrowUpRight, LockKeyhole } from 'lucide-react';

export const StudioDocs = () => <section id="studio" data-testid="studio-docs-section">
  <h2>Agent Studio / A working reference integration</h2>
  <p>COOKIE’s reference agents now run real OpenAI GPT-5.4 Mini requests through the Emergent AI gateway. Each task starts a new model session. The personal, coding, research and strategy roles use the same model, not separate third-party AI products. No browsing, transaction or external action tools are connected.</p>
  <Link className="btn btn-secondary" to="/app/studio" data-testid="docs-open-studio">Open Agent Studio <ArrowUpRight size={14}/></Link>
  <div className="docs-endpoints"><div><span className="method post">POST</span><code>/studio/prepare</code><span>Owner session, current permissions, encrypted context</span></div><div><span className="method post">POST</span><code>/studio/execute</code><span>Explicit one-task consent, live response stream</span></div><div><span className="method get">GET</span><code>/studio/runs</code><span>Metadata-only task receipts</span></div><div><span className="method post">POST</span><code>/studio/runs/:id/cancel</code><span>Stop the active owner-authorized task</span></div></div>
  <p>The browser requests only permitted encrypted memories and decrypts them locally after a passphrase check. It previews the exact task, selected content and recipient. Approval releases the selected plaintext to COOKIE’s authenticated reference runtime, the Emergent gateway and OpenAI. The passphrase and vault key never leave the browser.</p>
  <p>Prepared reviews expire after five minutes, bind the agent, task digest and memory versions, and are consumed once. The server checks ownership, connected status and current permissions again before dispatch; it also checks access during streaming. Changing a memory invalidates the old review. Private memories cannot be selected. The owner-provided plaintext is not a cryptographic proof of matching ciphertext; no ZK claim is made.</p>
  <div className="notice"><LockKeyhole size={17}/><span>COOKIE stores only receipt and access metadata, not task text, decrypted context or AI output. A response can be encrypted and saved by the user. Model/gateway processing and retention terms still apply; zero retention by third parties is not promised. Revocation and Stop block future use and stop the local task, but cannot recall context already sent or guarantee cancellation of provider billing.</span></div>
  <p>Comparison runs are independent real requests: with approved context and without vault context. No previous answers or model chat history are passed into either call. Copying a result is explicit; saving it uses the existing browser encryption flow. This owner-mediated runtime is not a general key-sharing service for external agents.</p>
</section>;