import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Bot, Plus, Search, ArrowUpRight, ShieldCheck, Plug } from 'lucide-react';
import { PageHeading, Btn, Modal, Empty } from '../components/Common';
import { AgentCard } from '../components/AgentCard';
import { Input } from '../components/ui/input';
import { toast } from '../components/ui/sonner';
import { useVault } from '../context/VaultContext';
import { api, errorMessage } from '../lib/api';
export default function Agents() {
  const { data, refresh } = useVault();
  const [modal, setModal] = useState(false); const [target, setTarget] = useState(null); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(''); const [developer, setDeveloper] = useState(''); const [kind, setKind] = useState('custom');
  const connect = async e => { e.preventDefault(); setBusy(true); try { await api.post('/agents', { name: name.trim(), developer: developer.trim() || 'Independent developer', kind }); await refresh(); setModal(false); setName(''); setDeveloper(''); setKind('custom'); toast.success('Agent connected. No memory is shared until you authorize it.'); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  const toggle = async () => { setBusy(true); try { await api.patch(`/agents/${target.id}`, { status: target.status === 'connected' ? 'disconnected' : 'connected' }); await refresh(); setTarget(null); toast.success(target.status === 'connected' ? 'Agent disconnected. All permissions revoked.' : 'Agent reconnected. Grant permissions to restore access.'); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="CONTEXT, NOT OWNERSHIP" title="Your circle of agents." subtitle="Choose who remembers what. You’re always in control."><Btn data-testid="connect-agent" onClick={() => setModal(true)}><Plus size={17}/> Connect Agent</Btn></PageHeading><div className="inline-info" data-testid="agent-demo-disclosure"><Bot size={17}/><p>Agent Studio runs these identities through a real GPT-5.4 Mini reference runtime. External agents connect separately through the API.</p><Link data-testid="agent-studio-link" to="/app/studio">Open Agent Studio <ArrowUpRight size={14}/></Link></div>
    {data.agents.length ? <div className="agents-grid">{data.agents.map(agent => <AgentCard key={agent.id} agent={agent} memories={data.memories} onToggle={setTarget}/>)}</div> : <Empty icon={Bot} title="Good agents need good context." text="Connect your first agent and choose its permissions."/>}
    {!data.agents.some(a => a.kind === 'research') && <div className="discover-agent"><Search size={28}/><div><span className="eyebrow">EXPAND YOUR CONTEXT</span><h2>Meet Research Agent.</h2><p>A research role for your approved knowledge context. No live browsing or external action tools.</p></div><Btn variant="secondary" data-testid="connect-research-agent" onClick={() => { setName('Research Agent'); setDeveloper('COOKIE Labs'); setKind('research'); setModal(true); }}>Connect <Plus size={15}/></Btn></div>}
    <Modal open={modal} onClose={() => setModal(false)} title="Make a new connection." description="Register an agent identity. No access is granted automatically." testId="connect-agent-dialog"><form className="form-stack" onSubmit={connect}><label htmlFor="agent-name">Agent name</label><Input id="agent-name" data-testid="agent-name-input" className="field" placeholder="e.g. My Research Agent" value={name} onChange={e => setName(e.target.value)} required maxLength={80}/><label htmlFor="agent-developer">Developer</label><Input id="agent-developer" data-testid="agent-developer-input" className="field" placeholder="Your name or organization" value={developer} onChange={e => setDeveloper(e.target.value)} maxLength={80}/><div className="notice"><ShieldCheck size={16}/><span>A connection registers this agent in your vault. An API key and explicit permissions are needed for actual requests.</span></div><Btn type="submit" data-testid="save-agent" busy={busy} disabled={!name.trim()}><Plug size={16}/> Connect agent</Btn></form></Modal>
    <Modal open={Boolean(target)} onClose={() => setTarget(null)} title={target?.status === 'connected' ? 'Disconnect this agent?' : 'Reconnect this agent?'} description={target?.status === 'connected' ? `All permissions for ${target?.name} will be revoked immediately. Existing keys cannot be used while disconnected.` : 'Previously revoked permissions stay revoked. Grant new permissions after reconnecting.'} testId="agent-status-dialog"><div className="dialog-actions"><Btn variant="secondary" data-testid="cancel-agent-toggle" onClick={() => setTarget(null)}>Cancel</Btn><Btn data-testid="confirm-agent-toggle" busy={busy} onClick={toggle}>{target?.status === 'connected' ? 'Disconnect agent' : 'Reconnect agent'}</Btn></div></Modal>
  </>;
}