import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Bot, Plus, Code2, TrendingUp, Search, UserRound, ArrowUpRight, ShieldCheck, Unplug, Plug, Copy } from 'lucide-react';
import { PageHeading, Btn, Badge, Modal, Empty } from '../components/Common';
import { Input } from '../components/ui/input';
import { toast } from '../components/ui/sonner';
import { useVault } from '../context/VaultContext';
import { api, errorMessage, relativeTime } from '../lib/api';
const icons = { personal: UserRound, trading: TrendingUp, coding: Code2, research: Search, custom: Bot };
export default function Agents() {
  const { data, refresh } = useVault();
  const [modal, setModal] = useState(false); const [target, setTarget] = useState(null); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(''); const [developer, setDeveloper] = useState(''); const [kind, setKind] = useState('custom');
  const connect = async e => { e.preventDefault(); setBusy(true); try { await api.post('/agents', { name: name.trim(), developer: developer.trim() || 'Independent developer', kind }); await refresh(); setModal(false); setName(''); setDeveloper(''); setKind('custom'); toast.success('Agent connected. No memory is shared until you authorize it.'); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  const toggle = async () => { setBusy(true); try { await api.patch(`/agents/${target.id}`, { status: target.status === 'connected' ? 'disconnected' : 'connected' }); await refresh(); setTarget(null); toast.success(target.status === 'connected' ? 'Agent disconnected. All permissions revoked.' : 'Agent reconnected. Grant permissions to restore access.'); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="CONTEXT, NOT OWNERSHIP" title="Your circle of agents." subtitle="Choose who remembers what. You’re always in control."><Btn data-testid="connect-agent" onClick={() => setModal(true)}><Plus size={17}/> Connect Agent</Btn></PageHeading><div className="inline-info" data-testid="agent-demo-disclosure"><Bot size={17}/><p>Sample agents are demo identities. Connect your own agent through the COOKIE API.</p><Link data-testid="agent-api-link" to="/app/api">Explore API <ArrowUpRight size={14}/></Link></div>
    {data.agents.length ? <div className="agents-grid">{data.agents.map(agent => { const Icon = icons[agent.kind] || Bot; const memories = data.memories.filter(m => m.agent_ids.includes(agent.id)); return <article className="agent-card" key={agent.id} data-testid={`agent-card-${agent.id}`}><div className="agent-card-top"><span className={`agent-icon large ${agent.kind}`}><Icon size={25}/></span><Badge tone={agent.status === 'connected' ? 'green' : ''} testId={`agent-status-${agent.id}`}><i className="small-dot"/>{agent.status === 'connected' ? 'Connected' : 'Disconnected'}</Badge></div><div className="agent-name"><h2>{agent.name}</h2><span className="mini-tag">{agent.type === 'demo' ? 'DEMO' : 'CUSTOM'}</span></div><p className="agent-developer">by {agent.developer}</p><div className="agent-id"><span className="mono" data-testid={`agent-id-${agent.id}`}>{agent.id}</span><button data-testid={`copy-agent-id-${agent.id}`} className="icon-button" title="Copy agent ID" aria-label="Copy agent ID" onClick={() => navigator.clipboard.writeText(agent.id).then(() => toast.success('Agent ID copied.')).catch(() => toast.error('Clipboard is unavailable.'))}><Copy size={13}/></button></div><div className="agent-access"><span className="field-label">AUTHORIZED MEMORIES</span><div>{memories.length ? memories.slice(0, 3).map(m => <span className="access-chip" key={m.id}><LockIcon/>{m.title}</span>) : <span className="muted-text">No memory access</span>}{memories.length > 3 && <span>+{memories.length - 3} more</span>}</div></div><div className="agent-last">Last activity <span>{relativeTime(agent.last_activity)}</span></div><div className="agent-actions"><Link className="text-link" to="/app/permissions" data-testid={`agent-permissions-${agent.id}`}><ShieldCheck size={14}/> Permissions <ArrowUpRight size={13}/></Link><button className="icon-button" title={agent.status === 'connected' ? 'Disconnect agent' : 'Reconnect agent'} aria-label={`${agent.status === 'connected' ? 'Disconnect' : 'Reconnect'} ${agent.name}`} data-testid={`toggle-agent-${agent.id}`} onClick={() => setTarget(agent)}>{agent.status === 'connected' ? <Unplug size={17}/> : <Plug size={17}/>}</button></div></article>; })}</div> : <Empty icon={Bot} title="Good agents need good context." text="Connect your first agent and choose its permissions."/>}
    {!data.agents.some(a => a.kind === 'research') && <div className="discover-agent"><Search size={28}/><div><span className="eyebrow">EXPAND YOUR CONTEXT</span><h2>Meet Research Agent.</h2><p>A demo identity for your knowledge and research context.</p></div><Btn variant="secondary" data-testid="connect-research-agent" onClick={() => { setName('Research Agent'); setDeveloper('COOKIE Labs'); setKind('research'); setModal(true); }}>Connect <Plus size={15}/></Btn></div>}
    <Modal open={modal} onClose={() => setModal(false)} title="Make a new connection." description="Register an agent identity. No access is granted automatically." testId="connect-agent-dialog"><form className="form-stack" onSubmit={connect}><label htmlFor="agent-name">Agent name</label><Input id="agent-name" data-testid="agent-name-input" className="field" placeholder="e.g. My Research Agent" value={name} onChange={e => setName(e.target.value)} required maxLength={80}/><label htmlFor="agent-developer">Developer</label><Input id="agent-developer" data-testid="agent-developer-input" className="field" placeholder="Your name or organization" value={developer} onChange={e => setDeveloper(e.target.value)} maxLength={80}/><div className="notice"><ShieldCheck size={16}/><span>A connection registers this agent in your vault. An API key and explicit permissions are needed for actual requests.</span></div><Btn type="submit" data-testid="save-agent" busy={busy} disabled={!name.trim()}><Plug size={16}/> Connect agent</Btn></form></Modal>
    <Modal open={Boolean(target)} onClose={() => setTarget(null)} title={target?.status === 'connected' ? 'Disconnect this agent?' : 'Reconnect this agent?'} description={target?.status === 'connected' ? `All permissions for ${target?.name} will be revoked immediately. Existing keys cannot be used while disconnected.` : 'Previously revoked permissions stay revoked. Grant new permissions after reconnecting.'} testId="agent-status-dialog"><div className="dialog-actions"><Btn variant="secondary" data-testid="cancel-agent-toggle" onClick={() => setTarget(null)}>Cancel</Btn><Btn data-testid="confirm-agent-toggle" busy={busy} onClick={toggle}>{target?.status === 'connected' ? 'Disconnect agent' : 'Reconnect agent'}</Btn></div></Modal>
  </>;
}
const LockIcon = () => <ShieldCheck size={11}/>;