import { useState, useEffect, useCallback } from 'react';
import { KeyRound, Plus, Activity, Database, ArrowDownLeft, Eye, RotateCw, Trash2, Play, ShieldCheck } from 'lucide-react';
import { PageHeading, Stat, Btn, Badge, Empty, SectionHeading } from '../components/Common';
import { toast } from '../components/ui/sonner';
import { useVault } from '../context/VaultContext';
import { api, API_URL, errorMessage, relativeTime } from '../lib/api';
import { DocsContent } from './Docs';
import { DeveloperDialogs } from '../components/DeveloperDialogs';
export default function Developer() {
  const { data, refresh } = useVault(); const [tab, setTab] = useState('Overview'); const [keys, setKeys] = useState([]); const [stats, setStats] = useState({ total: 0, reads: 0, writes: 0, active_agents: 0, error_rate: 0, logs: [] });
  const [newKey, setNewKey] = useState(false); const [name, setName] = useState(''); const [agent, setAgent] = useState(''); const [canWrite, setCanWrite] = useState(false); const [secret, setSecret] = useState(null); const [secrets, setSecrets] = useState({}); const [pending, setPending] = useState(null); const [busy, setBusy] = useState(false); const [testing, setTesting] = useState(false); const [testKey, setTestKey] = useState(''); const [result, setResult] = useState(null);
  const load = useCallback(async () => { const [k, s] = await Promise.all([api.get('/keys'), api.get('/developer/stats')]); setKeys(k.data); setStats(s.data); }, []);
  useEffect(() => { load().catch(e => toast.error(errorMessage(e))); }, [load]);
  const remember = response => { setSecrets(s => ({ ...s, [response.record.id]: response.key })); setSecret(response.key); };
  const create = async e => { e.preventDefault(); setBusy(true); try { const r = (await api.post('/keys', { name: name.trim(), agent_id: agent, can_write: canWrite })).data; remember(r); setNewKey(false); setName(''); setCanWrite(false); await load(); await refresh(); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  const apply = async () => { setBusy(true); try { if (pending.action === 'rotate') { const r = (await api.post(`/keys/${pending.key.id}/rotate`)).data; remember(r); } else { await api.delete(`/keys/${pending.key.id}`); toast.success('API key revoked immediately.'); } setSecrets(s => { const copy = { ...s }; delete copy[pending.key.id]; return copy; }); setPending(null); await load(); await refresh(); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  const testRequest = async e => { e.preventDefault(); setBusy(true); setResult(null); try { const r = await fetch(`${API_URL}/v1/memory`, { headers: { Authorization: `Bearer ${testKey}` } }); const json = await r.json(); setResult({ status: r.status, text: r.ok ? `${json.length} authorized encrypted ${json.length === 1 ? 'memory' : 'memories'} returned. No plaintext exposed.` : json.detail }); await load(); await refresh(); } catch { setResult({ status: 'Network error', text: 'Could not reach the API. Try again.' }); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="BUILD WITH CONTEXT" title="Good memory. Great agents." subtitle="Your gateway to the COOKIE memory layer."><Btn data-testid="create-api-key" onClick={() => { setAgent(data.agents.find(a => a.status === 'connected')?.id || ''); setNewKey(true); }}><Plus size={16}/> Create API Key</Btn></PageHeading><div className="page-tabs developer-tabs">{['Overview', 'API Keys', 'Documentation'].map(t => <button data-testid={`developer-tab-${t.toLowerCase().replace(' ', '-')}`} className={t === tab ? 'active' : ''} key={t} onClick={() => setTab(t)}>{t}</button>)}<span className="developer-env"><i className="small-dot"/> Demo environment</span></div>
    {tab === 'Documentation' ? <DocsContent/> : <>{tab === 'Overview' && <><div className="stats-grid developer-stats"><Stat icon={Activity} label="API requests" value={stats.total.toLocaleString()} sub="Actual requests to your agents" testId="api-requests"/><Stat icon={ArrowDownLeft} label="Memory reads" value={stats.reads.toLocaleString()} sub="Successful read requests" testId="api-reads"/><Stat icon={Database} label="Memory writes" value={stats.writes.toLocaleString()} sub="Successful write requests" testId="api-writes"/><Stat icon={ShieldCheck} label="Error rate" value={`${stats.error_rate}%`} sub={`${stats.active_agents} active requesting agents`} testId="api-errors"/></div><section className="api-request-section"><SectionHeading title="Recent API requests"><Btn variant="secondary" data-testid="test-api-request" onClick={() => { setTesting(true); setResult(null); setTestKey(''); }}><Play size={13}/> Test a request</Btn></SectionHeading>{stats.logs.length ? <div className="request-table-wrap"><table className="request-table" data-testid="api-request-log"><thead><tr><th>Request</th><th>Status</th><th>Agent</th><th>Time</th></tr></thead><tbody>{stats.logs.slice(0, 10).map(log => <tr key={log.id}><td><span className={`method ${log.method.toLowerCase()}`}>{log.method}</span><code>{log.path.replace('/api', '')}</code></td><td><Badge tone={log.status < 400 ? 'green' : 'red'}>{log.status} {log.status < 400 ? 'OK' : 'Denied'}</Badge></td><td>{data.agents.find(a => a.id === log.agent_id)?.name || log.agent_id}</td><td>{relativeTime(log.timestamp)}</td></tr>)}</tbody></table></div> : <Empty icon={Activity} title="Ready for your first request." text="Create a key, grant a permission, and give the API a try."/>}</section></>}
    <section className="api-key-section"><SectionHeading title="Your API keys"><span className="muted-text">{keys.filter(k => !k.revoked_at).length} active</span></SectionHeading><div className="notice" data-testid="api-key-warning"><KeyRound size={16}/><span>Never expose API keys in frontend code. Keys are agent-scoped, stored as hashes, and shown once. These are working demo-environment credentials.</span></div>{keys.length ? <div className="api-key-list">{keys.map(k => <div className={`api-key-row ${k.revoked_at ? 'revoked-key' : ''}`} data-testid={`api-key-${k.id}`} key={k.id}><span className="key-icon"><KeyRound size={20}/></span><div className="key-detail"><strong>{k.name} {k.revoked_at && <Badge>Revoked</Badge>}</strong><code>{k.prefix}••••••••••••</code><small>{data.agents.find(a => a.id === k.agent_id)?.name} · {k.can_write ? 'Read & write' : 'Read only'} · Created {new Date(k.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</small></div>{!k.revoked_at && <div className="key-actions"><button data-testid={`reveal-key-${k.id}`} title="Reveal key" aria-label="Reveal key" className="icon-button" onClick={() => secrets[k.id] ? setSecret(secrets[k.id]) : toast.info('This secret is no longer available. Rotate the key to create a new one.')}><Eye size={16}/></button><button data-testid={`rotate-key-${k.id}`} title="Rotate key" aria-label="Rotate key" className="icon-button" onClick={() => setPending({ action: 'rotate', key: k })}><RotateCw size={16}/></button><button data-testid={`revoke-key-${k.id}`} title="Revoke key" aria-label="Revoke key" className="icon-button" onClick={() => setPending({ action: 'revoke', key: k })}><Trash2 size={16}/></button></div>}</div>)}</div> : <Empty icon={KeyRound} title="Your first key opens possibilities." text="API keys connect authorized agents to encrypted memory."/>}</section></>}
    <DeveloperDialogs mode={secret ? 'secret' : pending ? 'action' : newKey ? 'create' : testing ? 'test' : null} onClose={() => { setNewKey(false); setSecret(null); setPending(null); setTesting(false); setTestKey(''); setResult(null); }} busy={busy} agents={data.agents} name={name} setName={setName} agent={agent} setAgent={setAgent} canWrite={canWrite} setCanWrite={setCanWrite} create={create} secret={secret} pending={pending} apply={apply} testKey={testKey} setTestKey={setTestKey} testRequest={testRequest} result={result}/>
  </>;
}