import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowLeft, Copy, Download, LockKeyhole, Code2, ShieldCheck, Fingerprint, ArrowRight } from 'lucide-react';
import { Brand } from '../components/Brand';
import { API_URL } from '../lib/api';
import { toast } from '../components/ui/sonner';
export const CodeBlock = ({ code, title, testId }) => <div className="docs-code"><div className="code-top"><span>{title}</span><button className="icon-button" data-testid={`copy-${testId}`} title="Copy code" aria-label="Copy code" onClick={() => navigator.clipboard.writeText(code).then(() => toast.success('Code copied.')).catch(() => toast.error('Clipboard unavailable. Select the code to copy.'))}><Copy size={14}/></button></div><pre data-testid={testId}><code>{code}</code></pre></div>;
export const DocsContent = () => {
  const sdk = `// Proposed package interface — not published to npm yet.\nimport { CookieMemory } from "@cookie-ai/sdk";\n\nconst cookie = new CookieMemory({\n  baseUrl: process.env.COOKIE_API_URL,\n  apiKey: process.env.COOKIE_API_KEY,\n  decrypt: authorizedDecrypt, // user-authorized runtime\n  encrypt: authorizedEncrypt\n});\n\nconst memory = await cookie.getMemory({\n  user: walletAddress,\n  agent: agentId,\n  category: "Preferences"\n});\n\nconst response = await ai.generate({\n  context: memory,\n  message: userMessage\n});`;
  const write = `await cookie.storeMemory({\n  user: walletAddress,\n  title: "Communication preferences",\n  category: "Preferences",\n  content: "User prefers concise answers.",\n  privacy: "shareable"\n});\n\n// An agent can relinquish its own permissions.\nawait cookie.revokeAccess({\n  user: walletAddress,\n  agent: agentId\n});`;
  return <div className="docs-content"><section id="quickstart"><span className="eyebrow">COOKIE DEVELOPERS / V0.1</span><h1>A memory layer.<br/>Not another model.</h1><p className="docs-lead">Build your agent. Bring your model. Give it the context the user chooses to share.</p><div className="architecture-flow" data-testid="api-architecture">{['AI Agent', 'COOKIE SDK', 'COOKIE API', 'Permissions', 'Encrypted Store'].map((s, i) => <span key={s}>{i > 0 && <ArrowRight size={14}/>}<strong>{s}</strong></span>)}</div><div className="notice" data-testid="integration-disclosure"><Code2 size={18}/><span>Developers integrate COOKIE into their own agents. COOKIE does not directly control or connect to ChatGPT, Claude, or other AI products. Sample agents are demo identities, not live AI integrations.</span></div></section>
    <section id="http"><h2>01 / Start with the working HTTP API</h2><p>Connect an agent, make a memory shareable, grant access, then create an API key bound to that agent. The key determines the user and agent identity; request parameters cannot override it.</p><CodeBlock title="Terminal · authorized read" testId="http-example" code={`export COOKIE_API_URL="${API_URL}"\n# Load COOKIE_API_KEY from your server's secret environment.\n\ncurl "$COOKIE_API_URL/v1/memory?category=Preferences" \\\n  -H "Authorization: Bearer $COOKIE_API_KEY"`}/><div className="docs-endpoints"><div><span className="method get">GET</span><code>/v1/memory</code><span>Only authorized, encrypted memories</span></div><div><span className="method get">GET</span><code>/v1/memory/:id</code><span>403 without an active permission</span></div><div><span className="method post">POST</span><code>/v1/memory</code><span>Encrypted envelope only</span></div><div><span className="method post">POST</span><code>/v1/permissions/revoke</code><span>Relinquish this agent’s access</span></div></div><p className="fine-print">Writes require a write-enabled key AND an active category permission. Revoked keys and disconnected agents are rejected immediately. No plaintext memory is returned by these endpoints.</p></section>
    <section id="sdk"><h2>02 / The SDK interface</h2><p>The npm package below is a proposed interface. A working, dependency-free JavaScript HTTP adapter is available as a local module. Import it as <code>./cookie-sdk.js</code>, not from npm.</p><a className="btn btn-secondary" href="/cookie-sdk.js" download data-testid="download-sdk"><Download size={15}/> Download JavaScript adapter</a><CodeBlock code={sdk} title="your-agent.ts · proposed npm interface" testId="sdk-example"/><CodeBlock code={write} title="Write and revoke" testId="sdk-write-example"/></section>
    <section id="encryption"><h2>03 / Encryption is a boundary, not a badge</h2><div className="docs-facts"><div><LockKeyhole size={23}/><h3>Encrypted in the browser</h3><p>AES-256-GCM with fresh 96-bit nonces. Keys are derived from a passphrase with PBKDF2-SHA-256 and a random 128-bit salt, using 310,000 iterations.</p></div><div><ShieldCheck size={23}/><h3>Permission before retrieval</h3><p>The API verifies agent status and active permissions on every request. Private memory is never agent-readable. Disconnecting revokes all permissions.</p></div></div><p>The server stores encrypted content and a passphrase verification envelope. Titles, categories, identities, and access events are visible metadata. This is a centralized MVP, not a fully decentralized or security-certified protocol.</p><div className="notice"><LockKeyhole size={18}/><span>An API key does not decrypt memory. Agents receive ciphertext. Delivering readable AI context requires a separately authorized encryption/decryption adapter in a trusted runtime. Automatic key distribution to third-party agents is not implemented. Never send the vault passphrase or key to COOKIE’s API.</span></div><p>API key secrets are shown once and only hashes are stored. Never expose API keys in frontend code. The key inspector is a development tool, not an example of production credential placement.</p></section>
    <section id="protocol"><span className="mini-tag">PROTOTYPE ARCHITECTURE</span><h2>04 / Privacy verification for AI memory</h2><p>Private memory → Approved operation → Zero-knowledge proof → Verification. An agent could prove it has authorization, or completed an approved computation, without publishing the underlying private data.</p><div className="protocol-future"><Fingerprint size={33}/><div><h3>ZK Infrastructure — Coming in the protocol layer</h3><p>No ZK circuit, proof generation, on-chain verification, or blockchain transaction is implemented in this MVP.</p></div></div><p>Separate identity and privacy-proof interfaces leave room for EVM or Solana signature verification and future privacy adapters. Zcash is one potential ecosystem for independent future exploration. COOKIE is not a Zcash product, is not endorsed by Zcash, and has no active Zcash integration.</p></section>
  </div>;
};
export default function Docs() { return <div className="public-docs"><header className="landing-header"><div className="landing-nav wrap"><Link to="/" data-testid="docs-brand"><Brand/></Link><span className="docs-header-label">DEVELOPER DOCUMENTATION</span><Link to="/app" className="btn btn-secondary" data-testid="docs-open-app">Open app <ArrowUpRight size={15}/></Link></div></header><div className="docs-layout wrap"><aside className="docs-sidebar"><Link to="/" className="text-link" data-testid="docs-back"><ArrowLeft size={14}/> Back to COOKIE</Link><span className="eyebrow">BUILD WITH COOKIE</span>{[['quickstart', 'Overview'], ['http', 'HTTP API'], ['sdk', 'JavaScript adapter'], ['encryption', 'Encryption & permissions'], ['protocol', 'Protocol roadmap']].map(([id, title]) => <a href={`#${id}`} data-testid={`docs-nav-${id}`} key={id}>{title}</a>)}<span className="live-label"><i/>API v0.1 · Demo environment</span></aside><DocsContent/></div></div>; }