import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, LockKeyhole, ShieldCheck, MoveUpRight, Fingerprint, Code2, Check, Menu, X, Layers, UserRound, Bot, Braces } from 'lucide-react';
import { motion } from 'framer-motion';
import { Brand, CookieMark } from '../components/Brand';
import { Btn } from '../components/Common';
import { AuthDialog } from '../components/AuthDialog';
import { useVault } from '../context/VaultContext';
const reveal = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: .7 } };
export default function Landing() {
  const [auth, setAuth] = useState(null);
  const [menu, setMenu] = useState(false);
  const [usecase, setUsecase] = useState(0);
  const { user, key } = useVault();
  const scenarios = [
    { name: 'Your personal AI', icon: UserRound, category: 'PERSONAL CONTEXT', title: 'An introduction. Not a reset.', text: 'Your preferences, goals, and the little things that make you, you. Ready for your next assistant.', memory: 'Prefers concise, thoughtful answers', agent: 'Personal AI', status: 'Context authorized' },
    { name: 'Your coding agent', icon: Braces, category: 'DEVELOPER CONTEXT', title: 'Less setup. More building.', text: 'Your stack, coding conventions, and project context. A head start for every compatible coding agent.', memory: 'React · TypeScript · Small components', agent: 'Coding Agent', status: 'Work context authorized' },
    { name: 'Your research agent', icon: Layers, category: 'KNOWLEDGE CONTEXT', title: 'Pick up where you left off.', text: 'Your research interests and ideas stay connected. Even when you choose a different agent.', memory: 'Exploring private AI infrastructure', agent: 'Research Agent', status: 'Knowledge authorized' },
  ];
  const current = scenarios[usecase];
  return <div className="landing">
    <header className="landing-header"><div className="landing-nav wrap"><Link to="/" data-testid="landing-brand" aria-label="COOKIE home"><Brand/></Link><nav className={menu ? 'public-links mobile-open' : 'public-links'}><a href="#how-it-works" data-testid="nav-protocol" onClick={() => setMenu(false)}>The protocol</a><a href="#use-cases" data-testid="nav-usecases" onClick={() => setMenu(false)}>Use cases</a><a href="#privacy" data-testid="nav-privacy" onClick={() => setMenu(false)}>Privacy</a><Link to="/docs" data-testid="nav-developers">Developers <ArrowUpRight size={13}/></Link></nav><div className="nav-actions"><span className="live-label"><i/>Protocol preview</span>{user && key ? <Link className="btn btn-secondary" to="/app" data-testid="open-dashboard">Open app <ArrowUpRight size={15}/></Link> : <Btn variant="secondary" data-testid="connect-wallet" onClick={() => setAuth('create')}>Connect Wallet <ArrowUpRight size={15}/></Btn>}<button className="icon-button mobile-toggle" data-testid="mobile-menu" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X/> : <Menu/>}</button></div></div></header>
    <main>
      <section className="hero"><div className="hero-art" aria-hidden="true"><img src="/images/cookie-core.jpg" alt=""/></div><div className="hero-grid" aria-hidden="true"/><div className="wrap hero-inner"><motion.div {...reveal} className="hero-copy"><div className="release-pill" data-testid="hero-release"><span className="release-dot"/> COOKIE PROTOCOL <span className="release-version">v0.1 <ArrowUpRight size={11}/></span></div><h1 data-testid="hero-title">Private Memory<br/>for <span>AI.</span><span className="heading-period"/></h1><p className="hero-subtitle" data-testid="hero-subtitle">Own your AI memory.<br/>Carry it between agents.</p><div className="hero-buttons"><Btn data-testid="create-memory-hero" onClick={() => setAuth('create')}>Create Memory <ArrowUpRight size={17}/></Btn><Btn variant="ghost" data-testid="explore-demo" onClick={() => setAuth('demo')}><span className="play-icon">▷</span> Explore Demo</Btn></div><div className="hero-assurance" data-testid="hero-privacy"><LockKeyhole size={13}/><span>Encrypted.</span><span>Permissioned.</span><span>Portable.</span></div></motion.div><div className="art-caption" data-testid="hero-art-label"><span className="caption-cross">+</span><div>YOUR MEMORY. YOUR CORE.<br/><span>AES-256-GCM / CLIENT-SIDE ENCRYPTION</span></div></div><div className="art-top-label" aria-hidden="true"><span/>MEMORY, REIMAGINED.</div></div><div className="hero-bottom wrap"><span>YOUR AI CAN CHANGE. YOUR MEMORY DOESN’T HAVE TO.</span><a data-testid="discover-protocol" href="#how-it-works">Meet your memory layer <ArrowRight size={15}/></a></div></section>
      <section className="protocol-strip"><div className="wrap strip-inner"><span className="strip-label">ONE MEMORY LAYER.<br/><strong>EVERY AGENT YOU CHOOSE.</strong></span><div className="mini-flow"><span className="flow-entity"><Fingerprint size={21}/> You</span><span className="flow-line"/><span className="flow-cookie"><CookieMark/> COOKIE</span><span className="flow-line"/><div className="flow-agents"><span><Bot size={20}/> Personal AI</span><span><Code2 size={20}/> Coding Agent</span><span><Layers size={20}/> Research Agent</span></div></div></div></section>
      <section className="section wrap" id="how-it-works"><motion.div {...reveal} className="section-intro"><div><span className="eyebrow">CONTEXT WITHOUT COMPROMISE</span><h2>Your AI remembers you.<br/><span>You should own the memory.</span></h2></div><p>Not another chatbot. Not another silo.<br/>One private memory layer between you<br className="desktop-br"/> and the agents you choose.</p></motion.div><div className="steps-grid">{[{ n: '01', icon: LockKeyhole, title: 'Store privately.', text: 'Keep the context that matters. Encrypted in your browser, before it ever leaves.' }, { n: '02', icon: ShieldCheck, title: 'Authorize precisely.', text: 'The right agent. The right context. Give access on your terms, and revoke it anytime.' }, { n: '03', icon: MoveUpRight, title: 'Carry it forward.', text: 'Switch agents, not identities. Export your vault and bring your memory with you.' }].map((step, i) => <motion.article {...reveal} transition={{ delay: i * .1, duration: .6 }} className="step-item" key={step.n} data-testid={`step-${step.n}`}><div className="step-top"><step.icon size={24}/><span>{step.n} /</span></div><h3>{step.title}</h3><p>{step.text}</p><div className={`step-visual visual-${i}`} aria-hidden="true">{i === 0 ? <><span>e4 9f a2 8c 01 d7</span><LockKeyhole size={17}/><span>7b f0 21 c8 6a 93</span></> : i === 1 ? <><span><i/> Personal AI</span><Check size={16}/><span className="faded">Private notes <LockKeyhole size={12}/></span></> : <><CookieMark/><span className="small-flow-line"/><span className="export-file">.cookie.json <ArrowUpRight size={13}/></span></>}</div></motion.article>)}</div></section>
      <section className="usecase-band" id="use-cases"><div className="wrap section"><div className="section-intro"><div><span className="eyebrow">SAME YOU. NEW POSSIBILITIES.</span><h2>A little context.<br/><span>A world of difference.</span></h2></div><div className="usecase-tabs">{scenarios.map((s, i) => <button key={s.name} data-testid={`usecase-tab-${i}`} onClick={() => setUsecase(i)} className={usecase === i ? 'selected' : ''}><s.icon size={16}/>{s.name}</button>)}</div></div><div className="usecase-layout"><motion.div key={usecase} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="usecase-copy"><span className="mono accent">{current.category}</span><h3 data-testid="usecase-title">{current.title}</h3><p data-testid="usecase-description">{current.text}</p><button data-testid="try-usecase" className="text-link" onClick={() => setAuth('demo')}>Try it in the demo <ArrowUpRight size={16}/></button></motion.div><div className="usecase-animation" data-testid="animated-usecase"><span className="diagram-label">ILLUSTRATIVE DATA FLOW</span><div className="context-node"><LockKeyhole size={18}/><span key={current.memory}>{current.memory}</span><i/></div><div className="vertical-flow"/><div className="diagram-cookie"><CookieMark/></div><div className="vertical-flow"/><div className="agent-node" key={current.agent}><current.icon size={20}/><span>{current.agent}</span><ShieldCheck className="green" size={17}/></div><span className="flow-caption"><i/>{current.status}</span></div></div></div></section>
      <section className="section wrap privacy-section" id="privacy"><div className="privacy-symbol"><Fingerprint size={116} strokeWidth={.8}/><span className="orbit-lock"><LockKeyhole size={20}/></span></div><div className="privacy-copy"><span className="eyebrow">PRIVATE BY DESIGN</span><h2>Your memory.<br/><span>Your permissions.</span></h2><p>Agents get the context they need.<br/>They don’t get ownership of you.</p><div className="privacy-points"><span><Check/>Real browser encryption</span><span><Check/>Revocable agent access</span><span><Check/>An exportable encrypted vault</span></div><Link className="prototype-link" to="/docs#protocol" data-testid="zk-roadmap"><span className="mini-tag">UP NEXT</span> ZK infrastructure · Protocol layer <ArrowUpRight size={14}/></Link></div></section>
      <section className="developer-band"><div className="wrap developer-inner"><div><span className="eyebrow">BUILT FOR BUILDERS</span><h2>Give your AI<br/><span>a memory layer.</span></h2><p>Your agent. Your model. Your experience.<br/>COOKIE handles the permissioned memory layer.</p><Link className="btn btn-secondary" to="/docs" data-testid="read-docs">Read the Docs <ArrowUpRight size={16}/></Link></div><div className="landing-code"><div className="code-top"><span><i/><i/><i/></span><span>your-agent.ts</span><span className="mono">SDK PREVIEW</span></div><pre><code><span className="code-purple">const</span> memory = <span className="code-purple">await</span> cookie.<span className="code-gold">getMemory</span>({'{'}{'\n'}  user: <span className="code-green">walletAddress</span>,{'\n'}  agent: <span className="code-green">agentId</span>,{'\n'}  category: <span className="code-green">{'"Preferences"'}</span>{'\n'}{'}'});{'\n\n'}<span className="code-muted">{'// Context moves. Ownership stays.'}</span></code></pre><div className="code-foot"><LockKeyhole size={12}/> Permission-verified. Encrypted by default.</div></div></div></section>
      <section className="final-cta section wrap"><CookieMark/><h2>New agent.<br/><span>Still your memory.</span></h2><p>Give your AI a memory it can carry.</p><Btn data-testid="final-create-memory" onClick={() => setAuth('create')}>Create Your Memory <ArrowUpRight size={17}/></Btn></section>
    </main><footer className="landing-footer wrap"><Link to="/" data-testid="footer-brand"><Brand/></Link><span>Private Memory for AI.</span><div><Link to="/docs" data-testid="footer-docs">Documentation <ArrowUpRight size={13}/></Link><a href="#privacy" data-testid="footer-privacy">Privacy</a><span className="copyright">© {new Date().getFullYear()} COOKIE</span></div></footer>
    <AuthDialog open={Boolean(auth)} demo={auth === 'demo'} onClose={() => setAuth(null)}/>
  </div>;
}