import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Plus, Search, Database, LockKeyhole, ArrowUpRight, Trash2, Eye, ShieldCheck, Clock3, Bot } from 'lucide-react';
import { PageHeading, Btn, Badge, Modal, Empty } from '../components/Common';
import { MemoryDialog } from '../components/MemoryDialog';
import { AccessDialog } from '../components/AccessDialog';
import { useVault } from '../context/VaultContext';
import { api, CATEGORIES, relativeTime, errorMessage } from '../lib/api';
import { toast } from '../components/ui/sonner';
export default function Memory() {
  const { data, refresh } = useVault();
  const [searchParams, setSearchParams] = useSearchParams();
  const [dialog, setDialog] = useState(null); const [access, setAccess] = useState(null); const [deleting, setDeleting] = useState(null);
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('All categories'); const [tab, setTab] = useState('All memories'); const [busy, setBusy] = useState(false);
  useEffect(() => {
    if (searchParams.get('new')) { setDialog({}); setSearchParams({}, { replace: true }); }
    const m = data.memories.find(m => m.id === searchParams.get('view'));
    if (m) { setDialog(m); setSearchParams({}, { replace: true }); }
  }, [searchParams, data.memories, setSearchParams]);
  const filtered = data.memories.filter(m => m.title.toLowerCase().includes(search.toLowerCase()) && (category === 'All categories' || m.category === category) && (tab === 'All memories' || (tab === 'Private' ? m.privacy === 'private' : m.agent_ids.length > 0)));
  const remove = async () => { setBusy(true); try { await api.delete(`/memories/${deleting.id}`); await refresh(); setDeleting(null); toast.success('Memory permanently deleted.'); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="ENCRYPTED BY DEFAULT" title="Your memory vault." subtitle="A little about you. A lot of possibility."><Btn data-testid="add-memory" onClick={() => setDialog({})}><Plus size={17}/> Add Memory</Btn></PageHeading><div className="memory-toolbar"><div className="page-tabs">{['All memories', 'Private', 'Shared'].map(t => <button data-testid={`memory-tab-${t.toLowerCase().replace(' ', '-')}`} key={t} className={t === tab ? 'active' : ''} onClick={() => setTab(t)}>{t}{t === 'All memories' && <span>{data.memories.length}</span>}</button>)}</div><div className="filter-controls"><div className="search-field"><Search size={16}/><input aria-label="Search memories" data-testid="memory-search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search memories…"/></div><select className="field category-filter" data-testid="memory-category-filter" aria-label="Filter by category" value={category} onChange={e => setCategory(e.target.value)}>{['All categories', ...CATEGORIES].map(c => <option key={c}>{c}</option>)}</select></div></div>
    {filtered.length ? <div className="memory-grid">{filtered.map((m, index) => <article className="memory-card" style={{ animationDelay: `${index * .05}s` }} key={m.id} data-testid={`memory-card-${m.id}`}><div className="memory-card-top"><span className={`category-icon cat-${m.category.toLowerCase().replace(' ', '')}`}><Database size={21}/></span><Badge tone="green" testId={`memory-encrypted-${m.id}`}><LockKeyhole size={11}/> Encrypted</Badge><button className="icon-button delete-memory-button" title="Delete memory" aria-label={`Delete ${m.title}`} data-testid={`delete-memory-${m.id}`} onClick={() => setDeleting(m)}><Trash2 size={15}/></button></div><h2 data-testid={`memory-title-${m.id}`}>{m.title}</h2><span className="memory-category">{m.category}<span>·</span>{m.privacy === 'private' ? 'Private' : 'Shareable'}</span><div className="encrypted-preview" aria-hidden="true"><span>•••• •••••••• ••••• ••••••</span><span>•••••••• ••••• ••••••• ••••</span><LockKeyhole size={16}/></div><div className="memory-meta"><span data-testid={`memory-agents-${m.id}`}><Bot size={13}/>{m.agent_ids.length} {m.agent_ids.length === 1 ? 'agent' : 'agents'}</span><span><Clock3 size={12}/>{relativeTime(m.last_accessed)}</span></div><div className="memory-card-actions"><button data-testid={`view-memory-${m.id}`} onClick={() => setDialog(m)}><Eye size={14}/> View memory <ArrowUpRight size={13}/></button><button data-testid={`manage-access-${m.id}`} title="Manage access" aria-label={`Manage access to ${m.title}`} onClick={() => setAccess(m)}><ShieldCheck size={16}/></button></div></article>)}</div> : <Empty title={data.memories.length ? 'No memories found.' : 'Every good agent starts with context.'} text={data.memories.length ? 'Try a different search or category.' : 'Create your first encrypted memory.'}><Btn data-testid="empty-add-memory" onClick={() => setDialog({})}><Plus size={16}/> Add Memory</Btn></Empty>}
    <div className="page-security-note"><LockKeyhole size={14}/><span>Memory content is AES-256-GCM encrypted. Only authorized sessions can unlock it.</span><span className="mono">CLIENT-SIDE ENCRYPTION</span></div>
    {dialog && <MemoryDialog memory={dialog} onClose={() => setDialog(null)}/>} {access && <AccessDialog memory={data.memories.find(m => m.id === access.id) || access} onClose={() => setAccess(null)}/>}
    <Modal open={Boolean(deleting)} onClose={() => setDeleting(null)} title="Let this memory go?" description={`“${deleting?.title}” will be permanently deleted and its direct permissions revoked. This cannot be undone.`} testId="delete-memory-dialog"><div className="dialog-actions"><Btn variant="secondary" data-testid="cancel-delete-memory" onClick={() => setDeleting(null)}>Keep memory</Btn><Btn variant="danger" data-testid="confirm-delete-memory" busy={busy} onClick={remove}><Trash2 size={15}/> Delete permanently</Btn></div></Modal>
  </>;
}