import { Link, useNavigate } from 'react-router-dom';
import { Database, LockKeyhole, Bot, ShieldCheck, ArrowUpRight, Plus, Fingerprint, Code2 } from 'lucide-react';
import { useVault } from '../context/VaultContext';
import { PageHeading, Stat, SectionHeading, ActivityRows, Empty } from '../components/Common';
import { CookieMark } from '../components/Brand';
export default function Overview() {
  const { data } = useVault();
  const { memories, agents, permissions, activity } = data;
  const connected = agents.filter(a => a.status === 'connected');
  const shared = memories.filter(m => m.agent_ids.length);
  const navigate = useNavigate();
  return <><PageHeading eyebrow="YOUR PERSONAL MEMORY LAYER" title="A little more context." subtitle="Your memories. Your agents. All in your control."><Link to="/app/studio" className="btn btn-secondary" data-testid="overview-open-studio"><Bot size={16}/> Agent Studio</Link><Link to="/app/memory?new=1" className="btn btn-primary" data-testid="overview-add-memory"><Plus size={17}/> Add Memory</Link></PageHeading>
    <div className="stats-grid"><Stat icon={Database} label="Total memories" value={memories.length} sub={`${memories.length} encrypted and yours`} testId="stat-memories"/><Stat icon={LockKeyhole} label="Shared memories" value={shared.length} sub="With your explicit permission" testId="stat-shared"/><Stat icon={Bot} label="Connected agents" value={connected.length} sub="Context, without ownership" testId="stat-agents"/><Stat icon={ShieldCheck} label="Active permissions" value={permissions.length} sub="Revocable at any time" testId="stat-permissions"/></div>
    <section className="overview-flow"><div><span className="eyebrow">ONE VAULT. ENDLESS POSSIBILITIES.</span><h2>Your AI can change.<br/><span>Your memory doesn’t have to.</span></h2><Link to="/app/settings" className="text-link" data-testid="overview-export">Take your memory with you <ArrowUpRight size={15}/></Link></div><div className="overview-diagram"><div className="diagram-person"><Fingerprint size={28}/><span>You</span></div><div className="flow-line"/><div className="overview-cookie"><CookieMark/><span>COOKIE</span></div><div className="flow-line"/><div className="diagram-agent-list">{['Personal AI', 'Trading Agent', 'Coding Agent'].map(a => <div key={a}><Bot size={15}/>{a}<span className={`small-dot ${connected.some(c => c.name === a) ? '' : 'inactive'}`}/></div>)}</div></div></section>
    <div className="overview-columns"><section><SectionHeading title="Your memory vault"><Link to="/app/memory" data-testid="view-all-memories">View all <ArrowUpRight size={14}/></Link></SectionHeading>{memories.length ? <div className="overview-memories">{memories.slice(0, 3).map(m => <button key={m.id} className="overview-memory" data-testid={`overview-memory-${m.id}`} onClick={() => navigate(`/app/memory?view=${m.id}`)}><span className={`category-icon cat-${m.category.toLowerCase().replace(' ', '')}`}><Database size={19}/></span><span><strong>{m.title}</strong><small>{m.category} <span>·</span> <LockKeyhole size={11}/> Encrypted</small></span><ArrowUpRight size={16}/></button>)}</div> : <Empty title="Your vault is ready." text="Start with a preference, a project, or a little about you."/>}<div className="vault-summary"><ShieldCheck size={14}/><span>100% of your memory content is encrypted.</span></div></section><section><SectionHeading title="Recent activity"><Link to="/app/activity" data-testid="view-all-activity">View all <ArrowUpRight size={14}/></Link></SectionHeading>{activity.length ? <ActivityRows activity={activity.slice(0, 5)} agents={agents} prefix="recent"/> : <Empty title="A fresh start." text="Your vault activity will appear here."/>}</section></div>
    <section className="developer-nudge"><Code2 size={24}/><div><h2>Building an agent?</h2><p>Give it a permissioned memory layer.</p></div><Link to="/app/api" data-testid="overview-developer" className="btn btn-secondary">Explore the API <ArrowUpRight size={16}/></Link></section>
  </>;
}