import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, Bot, LockKeyhole, ArrowUpRight, Trash2 } from 'lucide-react';
import { PageHeading, Modal, Btn, Empty, SectionHeading } from '../components/Common';
import { Switch } from '../components/ui/switch';
import { toast } from '../components/ui/sonner';
import { useVault } from '../context/VaultContext';
import { api, CATEGORIES, errorMessage } from '../lib/api';
export default function Permissions() {
  const { data, refresh } = useVault(); const [pending, setPending] = useState(null); const [busy, setBusy] = useState(false);
  const agents = data.agents.filter(a => a.status === 'connected');
  const apply = async () => { setBusy(true); try {
    if (pending.permission) await api.delete(`/permissions/${pending.permission.id}`);
    else await api.post('/permissions', { agent_id: pending.agent.id, target_type: 'category', target: pending.category });
    await refresh(); toast.success(pending.permission ? 'Permission revoked immediately.' : 'Category permission granted.'); setPending(null);
  } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="YOUR RULES, ENFORCED" title="Permission, not possession." subtitle="The right context for the right agent. Nothing more."><Link to="/app/activity?filter=permissions" data-testid="permission-history" className="btn btn-secondary">Permission history <ArrowUpRight size={15}/></Link></PageHeading><div className="permission-summary"><ShieldCheck size={24}/><div><h2 data-testid="permission-count">{data.permissions.length} active permissions</h2><p>Private memories are never shared, even when their category is authorized.</p></div><span className="status-badge green"><i className="small-dot"/> You’re in control</span></div><SectionHeading title="Category access"><span className="muted-text">Applies to current and future shareable memories</span></SectionHeading>
    {agents.length ? <div className="permission-table-wrapper"><table className="permission-table" data-testid="permission-matrix"><thead><tr><th>Memory category</th>{agents.map(agent => <th key={agent.id}><Bot size={17}/><span>{agent.name}</span></th>)}</tr></thead><tbody>{CATEGORIES.map(category => <tr key={category}><td><span className={`category-indicator cat-${category.toLowerCase().replace(' ', '')}`}/>{category}<small>{data.memories.filter(m => m.category === category && m.privacy === 'shareable').length} shareable</small></td>{agents.map(agent => { const permission = data.permissions.find(p => p.agent_id === agent.id && p.target_type === 'category' && p.target === category); return <td key={agent.id}><Switch aria-label={`${agent.name} access to ${category}`} data-testid={`category-permission-${category.toLowerCase().replace(' ', '-')}-${agent.id}`} checked={Boolean(permission)} onCheckedChange={() => setPending({ agent, category, permission })}/></td>; })}</tr>)}</tbody></table></div> : <Empty icon={Bot} title="No agents to authorize yet." text="Connect an agent to set up category permissions."><Link to="/app/agents" data-testid="permissions-connect-agent" className="btn btn-primary">Connect an agent <ArrowUpRight size={15}/></Link></Empty>}
    <section className="individual-permissions"><SectionHeading title="Individual memory access"><Link to="/app/memory" data-testid="manage-individual-access">Manage in vault <ArrowUpRight size={14}/></Link></SectionHeading>{data.permissions.filter(p => p.target_type === 'memory').length ? data.permissions.filter(p => p.target_type === 'memory').map(p => { const agent = data.agents.find(a => a.id === p.agent_id); const memory = data.memories.find(m => m.id === p.target); return <div className="individual-permission" key={p.id} data-testid={`individual-permission-${p.id}`}><LockKeyhole size={18}/><div><strong>{memory?.title || 'Deleted memory'}</strong><span>{agent?.name || p.agent_id} <span>·</span> Read access</span></div><button className="icon-button" title="Revoke permission" aria-label={`Revoke ${agent?.name} access to ${memory?.title}`} data-testid={`revoke-permission-${p.id}`} onClick={() => setPending({ agent, category: memory?.title, permission: p })}><Trash2 size={16}/></button></div>; }) : <p className="muted-text" data-testid="no-individual-permissions">No individual memory permissions. Grant access from your memory vault.</p>}</section>
    <Modal open={Boolean(pending)} onClose={() => setPending(null)} title={pending?.permission ? 'Revoke this permission?' : 'Authorize this category?'} description={pending?.permission ? `${pending?.agent?.name} will lose this access immediately. Other individual or category grants still apply.` : `${pending?.agent?.name} can retrieve encrypted, shareable memories in ${pending?.category}, including future additions. Private memories remain inaccessible.`} testId="permission-confirm-dialog"><div className="dialog-actions"><Btn variant="secondary" data-testid="cancel-permission" onClick={() => setPending(null)}>Cancel</Btn><Btn data-testid="confirm-permission" busy={busy} onClick={apply}>{pending?.permission ? 'Revoke permission' : 'Grant permission'}</Btn></div></Modal>
  </>;
}