import { useState } from 'react';
import { Download, Upload, LockKeyhole, Copy, Trash2, Fingerprint } from 'lucide-react';
import { PageHeading, Btn, Modal } from '../components/Common';
import { Input } from '../components/ui/input';
import { toast } from '../components/ui/sonner';
import { TransferDialog } from '../components/TransferDialog';
import { useVault } from '../context/VaultContext';
import { api, errorMessage } from '../lib/api';
import { unlock } from '../lib/crypto';
export default function Settings() {
  const { user, data, refresh, setKey } = useVault(); const [importing, setImporting] = useState(false); const [deleting, setDeleting] = useState(false); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const exportVault = async () => { setBusy(true); try { const result = (await api.get('/vault/export')).data; const url = URL.createObjectURL(new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `cookie-vault-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); await refresh(); toast.success('Encrypted vault exported. Keep your passphrase safe.'); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  const clear = async e => { e.preventDefault(); setBusy(true); setError(''); try { await unlock(password, user.vault); await api.delete('/vault/memories'); await refresh(); setDeleting(false); setPassword(''); toast.success('All memories deleted and permissions revoked.'); } catch (e) { setError(e.response ? errorMessage(e) : e.message); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="THE KEYS ARE YOURS" title="Make yourself at home." subtitle="Your identity, your vault, your next move."/><section className="settings-section"><div className="settings-label"><Fingerprint size={22}/><h2>Crypto identity</h2><p>Your wallet identifies you.<br/>It doesn’t reveal your memory.</p></div><div className="settings-details"><div className="detail-row"><span>COOKIE ID</span><strong className="mono" data-testid="cookie-identity">{user.id}</strong></div><div className="detail-row"><span>Wallet address</span><div className="wallet-full"><strong className="mono" data-testid="full-wallet-address">{user.wallet_address}</strong><button data-testid="copy-wallet-address" className="icon-button" title="Copy wallet address" aria-label="Copy wallet address" onClick={() => navigator.clipboard.writeText(user.wallet_address).then(() => toast.success('Wallet address copied.')).catch(() => toast.error('Clipboard is unavailable.'))}><Copy size={14}/></button></div></div><div className="detail-row"><span>Authentication</span><span className="status-badge">Demo wallet · Browser identity</span></div><div className="detail-row"><span>Connected agents</span><strong data-testid="settings-agent-count">{data.agents.filter(a => a.status === 'connected').length}</strong></div><p className="fine-print">This MVP uses a centralized service and a browser-bound demo identity, not a signed wallet. Reconnect from this browser to return to your vault.</p></div></section>
    <section className="settings-section"><div className="settings-label"><Download size={22}/><h2>Portable memory</h2><p>Your AI can change.<br/>Your memory doesn’t have to.</p></div><div className="settings-details"><h3>Your context has no fixed address.</h3><p className="settings-description">Export your encrypted vault or bring memories from another COOKIE vault. Keep the original passphrase to unlock an export. Compatible COOKIE format only.</p><div className="transfer-actions"><Btn data-testid="export-memory" onClick={exportVault} busy={busy}><Download size={16}/> Export Memory</Btn><Btn data-testid="import-memory" variant="secondary" onClick={() => setImporting(true)}><Upload size={16}/> Import Memory</Btn></div><span className="fine-print">{data.memories.length} encrypted memories · Permissions stay behind</span></div></section>
    <section className="settings-section"><div className="settings-label"><LockKeyhole size={22}/><h2>Encryption & privacy</h2><p>Protected by real browser cryptography.</p></div><div className="settings-details"><div className="detail-row"><span>Memory encryption</span><strong>AES-256-GCM</strong></div><div className="detail-row"><span>Key derivation</span><strong>PBKDF2 · SHA-256 · 310,000 iterations</strong></div><div className="detail-row"><span>Key storage</span><strong>Browser session memory only</strong></div><div className="detail-row"><span>Zero-knowledge proofs</span><span className="status-badge">Future protocol layer</span></div><p className="fine-print" data-testid="settings-ai-privacy">Stored memory content is encrypted; metadata is not. Agent Studio opens only selected context in your browser and sends readable text through COOKIE and the Emergent gateway to OpenAI after per-task approval. COOKIE keeps no task or response history unless you explicitly save an encrypted result. Provider retention terms apply. External memory APIs remain ciphertext-only. No production security certification is claimed.</p><Btn variant="secondary" data-testid="settings-lock-vault" onClick={() => setKey(null)}><LockKeyhole size={15}/> Lock vault now</Btn></div></section>
    <section className="settings-section danger-section"><div className="settings-label"><Trash2 size={22}/><h2>A clean slate</h2><p>Some things are better forgotten.</p></div><div className="settings-details"><h3>Permanently delete all memories</h3><p className="settings-description">All memories are removed and every permission is revoked. Your identity, agents, and activity history remain. This cannot be undone.</p><Btn variant="danger" data-testid="delete-all-memories" onClick={() => { setDeleting(true); setError(''); setPassword(''); }}>Delete all memories <Trash2 size={15}/></Btn></div></section>
    {importing && <TransferDialog onClose={() => setImporting(false)}/>}<Modal open={deleting} onClose={() => setDeleting(false)} title="Delete your entire memory vault?" description="This removes all memory content permanently and revokes every permission. Enter your vault passphrase to confirm." testId="delete-vault-dialog"><form className="form-stack" onSubmit={clear}><label htmlFor="delete-password">Vault passphrase</label><Input id="delete-password" data-testid="delete-vault-passphrase" type="password" className="field" value={password} onChange={e => setPassword(e.target.value)} required/>{error && <p data-testid="delete-vault-error" role="alert" className="form-error">{error}</p>}<Btn data-testid="confirm-delete-vault" variant="danger" type="submit" busy={busy}>Delete all memories permanently</Btn></form></Modal>
  </>;
}